# Use the official Emscripten SDK image
FROM emscripten/emsdk:3.1.51

WORKDIR /app

# Copy the engine and the bridge code
COPY engine /app/engine
COPY wasm_bridge /app/wasm_bridge

# Create an output directory for the web files
RUN mkdir -p /app/frontend/public/wasm

# Compile command
# -I: Include paths
# -O3: Maximize performance optimization (Critical for Physics)
# -s WASM=1: Output WebAssembly
# -s MODULARIZE=1: Create a nice JS module loader
# --bind: Use Embind (the bindings.cpp file we made)
CMD emcc -O3 \
    -I/app/engine/include \
    /app/wasm_bridge/src/bindings.cpp \
    /app/engine/src/analyzer.cpp \
    -s WASM=1 \
    -s MODULARIZE=1 \
    -s EXPORT_NAME="WebROOTModule" \
    --bind \
    -o /app/frontend/public/wasm/webroot.js
